name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
    workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Use Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: "16" # lts

      # This build runs with path prefix for github pages (hosted on subdirectory),
      # for example https://<USER>.github.io/<REPO-NAME>/
      # See: https://www.11ty.dev/docs/config/#deploy-to-a-subdirectory-with-a-path-prefix
      - name: Install and Build for Github Pages 🔧
        run: |
          npm install
          npm run build
          # npm run build -- --pathprefix="${{ github.event.repository.name }}"
          # The above doesn't work anymore? :-/
          # also doesn't work with eleventy-img https://github.com/11ty/eleventy/issues/1641
          # We set pathprefix again via Node env, see below
        env:
          ELEVENTY_ENV: production
          BASE_URL: "https://${{ github.event.repository.owner.name }}.github.io/"
          PATH_PREFIX: "/${{ github.event.repository.name }}/"
      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: _site #the static site folder